### ISSUE TITLE
What is the use of switch(act).. EOSIO_API?

### ISSUE THREAD

**Issue by filipniziol** [kesar/twitbot#7]
What is the use of the below lines?
I tried to copy the logic, but it seems only error during .wast file generation.

switch (act) {
            EOSIO_API(twitbot, (tip)(withdraw)(claim))
        };

**Comment by kesar** [comment]
the reason is to try to catch transfer actions from eosio.token, you need to tweak a bit how you get the actions.

I didnt run it in few months, so it could be some code deprecated, I will try to run it with current mainnet and fix it 👍 

Similar to:

https://github.com/leordev/monstereos/blob/master/contracts/pet/pet.cpp#L282

**Comment by filipniziol** [comment]
Ok. Thanks!
